"""reservations 테이블 추가

Revision ID: 01b6cf566f89
Revises: 
Create Date: 2026-06-11 07:36:04.841274+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01b6cf566f89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('is_canceled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reserved_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('reservation_id', name=op.f('pk_reservations'))
    )
    op.create_index(op.f('ix_reservations_event_id'), 'reservations', ['event_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_event_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
