# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ccproto/payment/v1/payment.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ccproto/payment/v1/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ccproto/payment/v1/payment.proto\x12\x12\x63\x63proto.payment.v1B\x90\x01\n\x16\x63om.ccproto.payment.v1B\x0cPaymentProtoP\x01\xa2\x02\x03\x43PX\xaa\x02\x12\x43\x63proto.Payment.V1\xca\x02\x12\x43\x63proto\\Payment\\V1\xe2\x02\x1e\x43\x63proto\\Payment\\V1\\GPBMetadata\xea\x02\x14\x43\x63proto::Payment::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ccproto.payment.v1.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ccproto.payment.v1B\014PaymentProtoP\001\242\002\003CPX\252\002\022Ccproto.Payment.V1\312\002\022Ccproto\\Payment\\V1\342\002\036Ccproto\\Payment\\V1\\GPBMetadata\352\002\024Ccproto::Payment::V1'
# @@protoc_insertion_point(module_scope)
