# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ccproto/event/v1/event.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ccproto/event/v1/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63\x63proto/event/v1/event.proto\x12\x10\x63\x63proto.event.v1\",\n\x0fGetEventRequest\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\"N\n\x10GetEventResponse\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\x12\x1f\n\x0btotal_seats\x18\x02 \x01(\x05R\ntotalSeats2a\n\x0c\x45ventService\x12Q\n\x08GetEvent\x12!.ccproto.event.v1.GetEventRequest\x1a\".ccproto.event.v1.GetEventResponseB\x84\x01\n\x14\x63om.ccproto.event.v1B\nEventProtoP\x01\xa2\x02\x03\x43\x45X\xaa\x02\x10\x43\x63proto.Event.V1\xca\x02\x10\x43\x63proto\\Event\\V1\xe2\x02\x1c\x43\x63proto\\Event\\V1\\GPBMetadata\xea\x02\x12\x43\x63proto::Event::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ccproto.event.v1.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.ccproto.event.v1B\nEventProtoP\001\242\002\003CEX\252\002\020Ccproto.Event.V1\312\002\020Ccproto\\Event\\V1\342\002\034Ccproto\\Event\\V1\\GPBMetadata\352\002\022Ccproto::Event::V1'
  _globals['_GETEVENTREQUEST']._serialized_start=50
  _globals['_GETEVENTREQUEST']._serialized_end=94
  _globals['_GETEVENTRESPONSE']._serialized_start=96
  _globals['_GETEVENTRESPONSE']._serialized_end=174
  _globals['_EVENTSERVICE']._serialized_start=176
  _globals['_EVENTSERVICE']._serialized_end=273
# @@protoc_insertion_point(module_scope)
