# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ccproto.event.v1 import event_pb2 as ccproto_dot_event_dot_v1_dot_event__pb2


class EventServiceStub:
    """예약 서비스가 좌석 검증을 위해 호출 (#48: reservation→event 직접호출 대체)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEvent = channel.unary_unary(
                '/ccproto.event.v1.EventService/GetEvent',
                request_serializer=ccproto_dot_event_dot_v1_dot_event__pb2.GetEventRequest.SerializeToString,
                response_deserializer=ccproto_dot_event_dot_v1_dot_event__pb2.GetEventResponse.FromString,
                _registered_method=True)


class EventServiceServicer:
    """예약 서비스가 좌석 검증을 위해 호출 (#48: reservation→event 직접호출 대체)
    """

    def GetEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=ccproto_dot_event_dot_v1_dot_event__pb2.GetEventRequest.FromString,
                    response_serializer=ccproto_dot_event_dot_v1_dot_event__pb2.GetEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ccproto.event.v1.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ccproto.event.v1.EventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventService:
    """예약 서비스가 좌석 검증을 위해 호출 (#48: reservation→event 직접호출 대체)
    """

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ccproto.event.v1.EventService/GetEvent',
            ccproto_dot_event_dot_v1_dot_event__pb2.GetEventRequest.SerializeToString,
            ccproto_dot_event_dot_v1_dot_event__pb2.GetEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
