# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ccproto/reservation/v1/reservation.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ccproto/reservation/v1/reservation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ccproto/reservation/v1/reservation.proto\x12\x16\x63\x63proto.reservation.v1\">\n\x15GetReservationRequest\x12%\n\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"X\n\x16GetReservationResponse\x12%\n\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n\x07user_id\x18\x02 \x01(\tR\x06userId2\x85\x01\n\x12ReservationService\x12o\n\x0eGetReservation\x12-.ccproto.reservation.v1.GetReservationRequest\x1a..ccproto.reservation.v1.GetReservationResponseB\xa8\x01\n\x1a\x63om.ccproto.reservation.v1B\x10ReservationProtoP\x01\xa2\x02\x03\x43RX\xaa\x02\x16\x43\x63proto.Reservation.V1\xca\x02\x16\x43\x63proto\\Reservation\\V1\xe2\x02\"Ccproto\\Reservation\\V1\\GPBMetadata\xea\x02\x18\x43\x63proto::Reservation::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ccproto.reservation.v1.reservation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ccproto.reservation.v1B\020ReservationProtoP\001\242\002\003CRX\252\002\026Ccproto.Reservation.V1\312\002\026Ccproto\\Reservation\\V1\342\002\"Ccproto\\Reservation\\V1\\GPBMetadata\352\002\030Ccproto::Reservation::V1'
  _globals['_GETRESERVATIONREQUEST']._serialized_start=68
  _globals['_GETRESERVATIONREQUEST']._serialized_end=130
  _globals['_GETRESERVATIONRESPONSE']._serialized_start=132
  _globals['_GETRESERVATIONRESPONSE']._serialized_end=220
  _globals['_RESERVATIONSERVICE']._serialized_start=223
  _globals['_RESERVATIONSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
