# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ccproto.reservation.v1 import reservation_pb2 as ccproto_dot_reservation_dot_v1_dot_reservation__pb2


class ReservationServiceStub:
    """결제 서비스가 예매 소유자 검증을 위해 호출 (#48: payment→reservation 직접호출 대체)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReservation = channel.unary_unary(
                '/ccproto.reservation.v1.ReservationService/GetReservation',
                request_serializer=ccproto_dot_reservation_dot_v1_dot_reservation__pb2.GetReservationRequest.SerializeToString,
                response_deserializer=ccproto_dot_reservation_dot_v1_dot_reservation__pb2.GetReservationResponse.FromString,
                _registered_method=True)


class ReservationServiceServicer:
    """결제 서비스가 예매 소유자 검증을 위해 호출 (#48: payment→reservation 직접호출 대체)
    """

    def GetReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservation,
                    request_deserializer=ccproto_dot_reservation_dot_v1_dot_reservation__pb2.GetReservationRequest.FromString,
                    response_serializer=ccproto_dot_reservation_dot_v1_dot_reservation__pb2.GetReservationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ccproto.reservation.v1.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ccproto.reservation.v1.ReservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReservationService:
    """결제 서비스가 예매 소유자 검증을 위해 호출 (#48: payment→reservation 직접호출 대체)
    """

    @staticmethod
    def GetReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ccproto.reservation.v1.ReservationService/GetReservation',
            ccproto_dot_reservation_dot_v1_dot_reservation__pb2.GetReservationRequest.SerializeToString,
            ccproto_dot_reservation_dot_v1_dot_reservation__pb2.GetReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
