# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ccproto/auth/v1/auth.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ccproto/auth/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63\x63proto/auth/v1/auth.proto\x12\x0f\x63\x63proto.auth.v1B~\n\x13\x63om.ccproto.auth.v1B\tAuthProtoP\x01\xa2\x02\x03\x43\x41X\xaa\x02\x0f\x43\x63proto.Auth.V1\xca\x02\x0f\x43\x63proto\\Auth\\V1\xe2\x02\x1b\x43\x63proto\\Auth\\V1\\GPBMetadata\xea\x02\x11\x43\x63proto::Auth::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ccproto.auth.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.ccproto.auth.v1B\tAuthProtoP\001\242\002\003CAX\252\002\017Ccproto.Auth.V1\312\002\017Ccproto\\Auth\\V1\342\002\033Ccproto\\Auth\\V1\\GPBMetadata\352\002\021Ccproto::Auth::V1'
# @@protoc_insertion_point(module_scope)
