"""payment_histories 테이블 추가

Revision ID: 009cd896400e
Revises: 
Create Date: 2026-06-11 07:36:05.597860+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '009cd896400e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_histories',
    sa.Column('payment_history_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.PrimaryKeyConstraint('payment_history_id', name=op.f('pk_payment_histories'))
    )
    op.create_index(op.f('ix_payment_histories_reservation_id'), 'payment_histories', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_payment_histories_user_id'), 'payment_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_histories_user_id'), table_name='payment_histories')
    op.drop_index(op.f('ix_payment_histories_reservation_id'), table_name='payment_histories')
    op.drop_table('payment_histories')
    # ### end Alembic commands ###
